### ISSUE TITLE
Update and creating a good readme.

### ISSUE THREAD

**Issue by abhishek-sultaniya** [abhishek-sultaniya/Calculatefest#1]
Add readme sutiing and describing project.

**Comment by PiedPiper-18** [comment]
Hi @abhishek-sultaniya, I would like to work on this issue. Could you please assign it to me?

**Comment by abhishek-sultaniya** [comment]
> Hi @abhishek-sultaniya, I would like to work on this issue. Could you please assign it to me?

Cool,I am assigning you this.But describe all features in readme.
