### ISSUE TITLE
Bug in history.

### ISSUE THREAD

**Issue by abhishek-sultaniya** [abhishek-sultaniya/Calculatefest#3]
The bug in history needs to be sorted.

**Comment by PiedPiper-18** [comment]
> The bug in history needs to be sorted.

Hi @abhishek-sultaniya I would like to sort this bug. Please assign this issue to me.

**Comment by abhishek-sultaniya** [comment]
> > The bug in history needs to be sorted.
> 
> Hi @abhishek-sultaniya I would like to sort this bug. Please assign this issue to me.

Done.
