### ISSUE TITLE
Bug in 'more' button

### ISSUE THREAD

**Issue by PiedPiper-18** [abhishek-sultaniya/Calculatefest#6]
Hello @abhishek-sultaniya. The text display on the 'more' button needs to be changed to 'less' after the expansion of the calculator onclick.  Also, I would like to work on the same. It would be great if you could assign this to me.

**Comment by abhishek-sultaniya** [comment]
> Hello @abhishek-sultaniya. The text display on the 'more' button needs to be changed to 'less' after the expansion of the calculator onclick. Also, I would like to work on the same. It would be great if you could assign this to me.

Yes, @PiedPiper-18 you can definitely work on it.
